language: node_js
node_js:
  - "8.10"
before_install:
  - npm i -g npm@latest
install:
  - npm i
  - scripts/modules-init-travis.sh
before_script:
  - npm run lint
  - npm run spellcheck
deploy:
  provider: script
  script: npx deploy
  on:
    branch: master
