language: node_js
node_js:
  - "8.10"
before_install:
  - npm i -g npm@latest
install:
  - npm i
  - scripts/modules-init-travis.sh
jobs:
  include:
    - stage: lint
    - script: npm run lint
    - stage: test
    - script: npm run test
    - stage: spellcheck
    - script: npm run spellcheck
deploy:
  provider: script
  script: mkdir .aws
  script: printf "[smallwins]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\nregion=us-west-2\n" > .aws/credentials && 
  script: npx deploy
  script: rm -rf .aws
  on:
    branch: travis
