language: node_js
node_js:
  - "8.10"
before_install:
  - npm i -g npm@latest
install:
  - npm i
  - scripts/modules-init-travis.sh
script:
  - npm run lint
  - npm run spellcheck
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script: mkdir .aws
  script: printf "[jsf]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_acce- ss_key=${AWS_SECRET_ACCESS_KEY}\nregion=us-west-2\n" > .aws/credentials && 
  script: npx deploy
  script: rm -rf .aws
  on:
    branch: travis
