name: CI

on:
  push:
    branches:
      - ghci
      - !refs/heads/master
  pull_request:
    branches:
      - ghci
      - !refs/heads/master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Versions
      run: |
        node --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test
